### ISSUE TITLE
bug: sequence allocation algorithm has global, shared state

### ISSUE THREAD

**Issue by bartoszwalacik** [polyjdbc/polyjdbc#16]
since class `KeyGeneratorRegistry` has static map of `SequenceAllocation` objects,
current val of each sequence is global.

It means that new instance of PolyJDBC, feeded with new db connection, doesnt initiates
current states of sequences from db but takes stale values (possibly genereted for another database).

it causes pk vilation exceptions.

**Comment by adamdubiel** [comment]
Fixed & release: 0.6.1

**Comment by bartoszwalacik** [comment]
thanks a lot for this super fast fix !
