### ISSUE TITLE
Allow to set prefix length 

### ISSUE THREAD

**Issue by raupachz** [polyjdbc/polyjdbc#25]
MySQL InnoDB tables have a maximum key length of 767 bytes. If you create an index on a long VARCHAR column you can easily exceed that value. See this [issue for example](https://github.com/javers/javers/issues/455).

The trick is to add a prefix length after the column name:

```
CREATE INDEX idx_foo ON foo (col_name(length))
```

At the moment I don't see a way on how to do this with polyjdbc.

Reference
https://dev.mysql.com/doc/refman/5.5/en/create-index.html

**Comment by bartoszwalacik** [comment]
will be fixed in javers
