### ISSUE TITLE
PreparedStatement and ResultSet are not closed in AutoIncremented

### ISSUE THREAD

**Issue by nmihajlovski** [polyjdbc/polyjdbc#27]
This causes leaks when using with external (non-managed) transactions.

**Comment by bartoszwalacik** [comment]
released in 0.6.5

**Comment by bartoszwalacik** [comment]
released in javers 3.1.0

**Comment by nmihajlovski** [comment]
Thanks @bartoszwalacik for quickly taking care of this!
