### ISSUE TITLE
Support for Microsoft SQL Server 2008

### ISSUE THREAD

**Issue by mark1900** [polyjdbc/polyjdbc#34]
I am trying to use [Javers](https://javers.org/documentation/repository-configuration/) and I get the following exception because Sequences are not supported until Microsoft SQL Server 2012 -
 https://docs.microsoft.com/en-us/sql/t-sql/statements/create-sequence-transact-sql.

```
Caused by: org.polyjdbc.core.exception.SchemaManagerException: [DDL_ERROR] Failed to run DDL:
CREATE SEQUENCE jv_commit_pk_seq START WITH 1 INCREMENT BY 1
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Unknown object type 'SEQUENCE' used in a CREATE, DROP, or ALTER statement."},
```

Would it be possible to use the [IDENTITY](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property) type instead?

```sql
CREATE TABLE Persons (
    ID int IDENTITY(1,1) PRIMARY KEY,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255) NOT NULL,
    Age int
);
```

**Comment by bartoszwalacik** [comment]
@mark1900 have mercy, even Microsoft have ended support for this version https://blogs.msdn.microsoft.com/sqlreleaseservices/end-of-mainstream-support-for-sql-server-2008-and-sql-server-2008-r2/

**Comment by mark1900** [comment]
@bartoszwalacik  I agree this is a old version, though as I am integrating against Microsoft SQL Server 2008 Service Pack 4, support doesn't end till 09/07/2019.

[Microsoft LifeCycle Search for SQL Server](https://support.microsoft.com/en-gb/lifecycle/search?alpha=Microsoft%20SQL%20Server%202008%20Service%20Pack)


Products Released | Life Cycle Start Date | Mainstream Support End Date | Extended Support End Date | Service Pack Support End Date | Notes
-- | -- | -- | -- | -- | --
Microsoft SQL Server 2008 R2 Service Pack 1 | 12/07/2011 | Not Applicable | Not Applicable | 08/10/2013 | See the latest Service Pack listing for this product for the end of support dates.
Microsoft SQL Server 2008 R2 Service Pack 2 | 26/07/2012 | Not Applicable | Not Applicable | 13/10/2015 | See the latest Service Pack listing for this product for the end of support dates. For IA64 only, SP2 will be supported until 7/9/2019. For more information see the SQL Release Services blog at http://blogs.msdn.com/b/sqlreleaseservices/archive/2014/09/26/sql-server-2008-r2-service-pack-3-has-released.aspx
Microsoft SQL Server 2008 R2 Service Pack 3 | Review Note | 08/07/2014 | 09/07/2019 |   | The Lifecycle Start Date for SQL Server 2008 R2 SP3 is 9/26/2014. For up to 6 years of additional support beyond Extended Support, please see the Premium Assurance website.
Microsoft SQL Server 2008 Service Pack 1 | 31/03/2009 | Not Applicable | Not Applicable | 11/10/2011 | See the latest Service Pack listing for this product for the end of support dates.
Microsoft SQL Server 2008 Service Pack 2 | 24/09/2010 | Not Applicable | Not Applicable | 09/10/2012 | See the latest Service Pack listing for this product for the end of support dates.
Microsoft SQL Server 2008 Service Pack 3 | 06/10/2011 | Not Applicable | Not Applicable | 13/10/2015 | See the latest Service Pack listing for this product for the end of support dates. For IA64 only, SP3 will be supported until 7/9/2019. For more information see the SQL Release Services blog at http://blogs.msdn.com/b/sqlreleaseservices/archive/2014/09/30/sql-server-2008-service-pack-4-has-released.aspx
Microsoft SQL Server 2008 Service Pack 4 | 07/07/2014 | 08/07/2014 | 09/07/2019 |   | For up to 6 years of additional support beyond Extended Support, please see the Premium Assurance website.

 Note** Quoted from https://support.microsoft.com/en-gb/lifecycle/search

**Comment by bartoszwalacik** [comment]
I don't think that someone here would like to implement support for such old database

**Comment by mark1900** [comment]
On another note, some people have found that using IDENTITY column vs a SEQUENCE object can result in a large performance difference.  It still may be better to prefer use of the IDENTITY column, other than the previous use case I gave above.

* http://byobi.com/2012/09/sequence-vs-identity-performance-comparison/
* https://stackoverflow.com/questions/10062328/sequence-vs-identity/25159620#25159620

**Comment by bartoszwalacik** [comment]
Poly uses batch approach for sequence-based id generator (one sequence hit for 100 id values) 
so performance isn't  the issue

**Comment by mark1900** [comment]
I am hoping to find an alternative to using a SEQUENCE object.  Similar to Hibernate achieves, where the [identifier generators](http://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#identifiers-generators) can be either specified as IDENTITY, SEQUENCE or TABLE.  Let me know if I am wrong, though it looks like it might be easy to update this library to use a table based approach instead?

Would it be as simple as updating the following class methods?
* [MysqlDialect.java](https://github.com/polyjdbc/polyjdbc/blob/master/src/main/java/org/polyjdbc/core/dialect/MysqlDialect.java) 
```java
@Override
public String nextFromSequence(String sequenceName) {
    return "SELECT NEXT VALUE FOR "+sequenceName;
}
```
* [MsSqlDialectConstraints.java](https://github.com/polyjdbc/polyjdbc/blob/master/src/main/java/org/polyjdbc/core/dialect/MsSqlDialectConstraints.java)
```java
@Override
public String createSequence(String name) {
    return "CREATE SEQUENCE " + name + " START WITH 1 INCREMENT BY 1";
}
```


I noticed that MySQL doesn't support sequences - [MysqlDialect.java](https://github.com/polyjdbc/polyjdbc/blob/master/src/main/java/org/polyjdbc/core/dialect/MysqlDialect.java)
```java
@Override
public boolean supportsSequences() {
    return false;
}

public String nextFromSequence(String sequenceName) {
    throw new UnsupportedOperationException("MySQL dialect does not support sequences, check Dialect.supportsSequence() before trying to reach sequence!");
}
```
How does the MySql Dialect operate without sequences?

**Comment by adamdubiel** [comment]
I see a heated discussion here :) Im on vacation, so i will look into this
issue once i comeback. However as Bartosz noted, i dont know about changing
the whole MsSQL dialect for this single version of DB, but then hibernate
-like configurable approach sounds reasonable. Maybe you could consider
contributing?

**Comment by bartoszwalacik** [comment]
Btw, are you using Poly directly or with Javers?

**Comment by mark1900** [comment]
@bartoszwalacik The quick responses are definitely appreciated.

I currently working on a prototype and right now configuring a [Javers Repository](https://javers.org/documentation/repository-configuration/).

Will probably patch/update the library for my specific use either using AOP( AspectJ) or through a classpath override.  If this prototype works out, I might fork the PolyJDBC and Javers libraries and contribute the changes if I have the time.  @adamdubiel  Not sure if I have the time to implement a more configurable approach.

**Comment by bartoszwalacik** [comment]
Do you know that you can point another database in Javers Repository to store audit data? By default this is the same database which is used by application but you can change it and use the last version of MS SQL or even MongoDB.

**Comment by mark1900** [comment]
I don't wish to configure a separated database instance for Javers/PolyJDBC.  

In my current situation I wish to maintain one transaction context, so that database changes in my application (In my case using JPA) and PolyJDBC are either committed together or rolled-back together.  Otherwise without using a distributed transaction, I could see the Javers auditing log could becoming out-of-sync with my application database.

**Comment by bartoszwalacik** [comment]
Right

**Comment by mark1900** [comment]
Correct me if I am wrong, though it looks like the PolyJDBC implementation of the MySQL integration doesn't use a batch approach for sequence-based id generator for keys.

Instead [MysqlDialect.java](https://github.com/polyjdbc/polyjdbc/blob/master/src/main/java/org/polyjdbc/core/dialect/MysqlDialect.java) utilizes the "AUTO_INCREMENT" modifier via [KeyGeneratorFactory.java](https://github.com/polyjdbc/polyjdbc/blob/polyjdbc-0.7.1/src/main/java/org/polyjdbc/core/key/KeyGeneratorFactory.java#L15) which uses `return new AutoIncremented();` instead of the more common `return new SequenceAllocation(dialect);` .

I think this is highlighted by how Javers uses the MySQL AUTO_INCREMENT modifier in [FixedSchemaFactory.java](https://github.com/javers/javers/blob/javers-3.3.5/javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/FixedSchemaFactory.java#L174).

Does this sound correct?

Anyway I completely understanding reluctance to support older database versions as there is quite a bit of variation between versions - [Hibernate SQL Dialects Collection](https://docs.jboss.org/hibernate/orm/5.2/javadocs/org/hibernate/dialect/package-summary.html).

Also, do you think there would be any issues to replacing the current sequence mechanism with using generic [table sequencing](https://en.wikibooks.org/wiki/Java_Persistence/Identity_and_Sequencing#Table_sequencing)?

**Comment by bartoszwalacik** [comment]
@mark1900 I think that you are confusing MySQL with MS SQL.
MySql is a popular open source database with good tooling.
MS SQL is paid and closed database being sold by Microsoft. Developing code for MS SQL is really hard for Mac or Linux users. That's why we are not eager to do it

**Comment by mark1900** [comment]
@bartoszwalacik While it  might be for a typo (MySQL vs MS SQL), I definitely know the difference and use both databases frequently.  Sorry if there is any confusion, and I will try and be a bit clearer. 

Basically, I noticed that the MysqlDialect is implemented quite differently from the other dialects, and used this to contrast an earlier statement.

> Poly uses batch approach for sequence-based id generator (one sequence hit for 100 id values)
so performance isn't the issue

At one point I was exploring re-implementing the MsSqlDialect using a similar strategy used in the MysqlDialect (IDENTITY vs AUTO_INCREMENT) and realised it is quite a bit of changes for downstream projects to change.  After this initial research work, this lead me to a possible solution using table sequencing.

**Comment by bartoszwalacik** [comment]
ok, I get it, true,  looks like IDENTITY in MS SQL could be handled in the same way as AUTO_INCREMENT in MySQL
