### ISSUE TITLE
passive mode

### ISSUE THREAD

**Issue by bartoszwalacik** [polyjdbc/polyjdbc#6]
I need a 'passive' mode in PolyJdbc. In that mode connection should be obtained from ConnectionProvider, registered by user (and not directly from a DataSource).

In passive mode, Polly should not manage transactions and not call commit(), rollback() and connection.close()

Rationale, I'd like to have my transactions managed by Spring TransactionManager.

**Comment by adamdubiel** [comment]
Will do :)

**Comment by adamdubiel** [comment]
See fixes in development branch, published as `0.5.0-SNAPSHOT`.

**Comment by bartoszwalacik** [comment]
looks all right, release please
